name: build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install build-essential git && git clone https://github.com/toastynerd/nesasm && cd nesasm && make && cd .. && ./nesasm/bin/nesasm shuffle.asm
